version: 2
jobs:
  build:
    branches:
      only:
        - develop
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0 \
              awscli==1.11.76
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app  -f docker/Dockerfile .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      # - run:
      #     name: Run tests
      #     command: |
      #       docker-compose -f docker/docker-compose.test.yml up
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              login="$(aws ecr get-login --region ap-northeast-1)"
              ${login}
              docker tag ${APP_NAME}:"${CIRCLE_BRANCH}" "${ECR_ENDPOINT}/${APP_NAME}:${CIRCLE_BRANCH}"
              docker push "${ECR_ENDPOINT}/prototype-ci:${CIRCLE_BRANCH}"
            fi